Repository OZ-Coding-School/oz_03_main-004-FE, pull requests merged in 2024-07, with the labels that each got.

#1 ✅ Test: 첫 PR 테스트
  src/App.tsx
Labels: Test

#3 ✅ Test: third PR
  src/App.tsx
Labels: Test

#4 ✅ Test: Seunghye test
  src/App.tsx
Labels: Test

#5 ✅ Test: sumgin test
  src/App.tsx
Labels: Test

#6 chore: 초기설정
  .eslintrc.cjs
  src/App.tsx
  tsconfig.json
Labels: Test

#7 🔥 Re: use javascript
  .eslintrc.cjs
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/App.tsx
  src/index.css
  src/main.jsx
  src/main.tsx
  src/styles/global.css
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.js
Labels: Docs, Refactor, Chore, Change

#8 📦️ Chore: lint, prettier 설정
  .eslintignore
  .eslintrc.cjs
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: Chore

#9 Re: typescript -> javascript
  .eslintignore
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/App.tsx
  src/index.css
  src/main.jsx
  src/main.tsx
  src/styles/global.css
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.js
Labels: Docs, Chore, Change

#10 Chore: 테일윈드 초기설정
  public/landing-section1-png-v2.png
  public/landing-section1-png.png
  public/landing-section1-svg-v2.svg
  public/landing-section1-svg.svg
  public/landing-section2-png.png
  public/landing-section2-svg.svg
  public/landing-section3-png.png
  public/landing-section3-svg.svg
  public/potato.png
  tailwind.config.js
Labels: Chore, Change

#11 🔧 Change: css 파일 구조 변경
  src/App.css
  src/App.jsx
  src/index.css
  src/styles/global.css
  tailwind.config.js
Labels: Docs, Change

#12 🔧 Change: pretendard 폰트 설정 및 이미지 파일 구조 변경
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  public/landing/landing-section1-png-v2.png
  public/landing/landing-section1-png.png
  public/landing/landing-section1-svg-v2.svg
  public/landing/landing-section1-svg.svg
  public/landing/landing-section2-png.png
  public/landing/landing-section2-svg.svg
  public/landing/landing-section3-png.png
  public/landing/landing-section3-svg.svg
  src/styles/global.css
Labels: Design, Change

#13 📦️ Chore: axios, dotenv 설치 및 파일구조 변경
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  public/landing/landing-section1-svg-2.svg
  src/App.jsx
  src/components/header/index.jsx
  src/main.jsx
  src/pages/landing/index.jsx
  src/pages/signin/index.jsx
  src/pages/signup/index.jsx
Labels: Docs, Chore, Change

#14 📦️ Chore: tailwind 적용
  package-lock.json
  package.json
  postcss.config.js
  src/App.jsx
  src/components/header/index.jsx
  src/main.jsx
  src/styles/global.css
  tailwind.config.js
  vite.config.js
Labels: Fix, Chore

#15 초기설정
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  postcss.config.js
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  public/landing/landing-section1-png-v2.png
  public/landing/landing-section1-png.png
  public/landing/landing-section1-svg-2.svg
  public/landing/landing-section1-svg-v2.svg
  public/landing/landing-section1-svg.svg
  public/landing/landing-section2-png.png
  public/landing/landing-section2-svg.svg
  public/landing/landing-section3-png.png
  public/landing/landing-section3-svg.svg
  public/potato.png
  src/App.css
  src/App.jsx
  src/components/header/index.jsx
  src/index.css
  src/main.jsx
  src/pages/landing/index.jsx
  src/pages/signin/index.jsx
  src/pages/signup/index.jsx
  src/styles/global.css
  tailwind.config.js
  vite.config.js
Labels: Docs, Chore, Change

#16 ✨ Feat: landing페이지 제작
  .eslintrc.cjs
  public/landing/landing-section1-png-v2.png
  public/landing/landing-section1-png.png
  public/landing/landing-section1-svg-2.svg
  public/landing/landing-section1-svg-v2.svg
  public/landing/landing-section1-svg.svg
  public/landing/landing-section2-png.png
  public/landing/landing-section2-svg.svg
  public/landing/landing-section3-png.png
  public/landing/landing-section3-svg.svg
  public/landing/pipe.svg
  public/landing/potato.jpeg
  public/landing/section1.svg
  public/landing/section2.svg
  public/landing/section3.svg
  public/landing/wave.svg
  public/landing/wave2.svg
  src/App.jsx
  src/components/footer/index.jsx
  src/components/header/index.jsx
  src/pages/landing/index.jsx
  tailwind.config.js
Labels: Feat, Design, Chore, Change

#17 ✨ Feat: signUp 페이지 제작
  package-lock.json
  src/components/common/input/index.jsx
  src/pages/signup/index.jsx
  src/styles/global.css
Labels: Feat, Design, Chore, Change

#21 ✨ Feat: 로그인 기능 구현
  package-lock.json
  package.json
  src/pages/signin/index.jsx
Labels: Fix, Docs, Feat, Chore

#22 ♻️ Refactor: axios 주석처리
  src/pages/signin/index.jsx
Labels: Refactor

#23 ✨ Feat: Setting 페이지 제작
  src/App.jsx
  src/pages/setting/index.jsx
  src/pages/signin/index.jsx
  src/pages/signup/index.jsx
Labels: Feat, Design

#24 ✨ Feat: Collection 컴포넌트 작성
  public/collection/basicpotato.svg
  public/collection/downarrow.svg
  public/collection/potato.svg
  public/collection/uparrow.svg
  src/App.jsx
  src/components/shared/collection/index.jsx
  src/pages/profile/index.jsx
Labels: Feat, Chore

#25 ✨ Feat: calendar 컴포넌트 제작
  package-lock.json
  package.json
  public/button/left.svg
  public/button/right.svg
  public/button/write.svg
  public/landing/section1.svg
  public/potato.png
  public/vite.svg
  src/App.jsx
  src/components/layout/footer/index.jsx
  src/components/layout/header/index.jsx
  src/components/shared/calendar/index.jsx
  src/components/shared/info/index.jsx
  src/components/shared/potato/index.jsx
  src/components/shared/stack/index.jsx
  src/components/shared/todo/index.jsx
  src/hooks/useCalendar/index.jsx
  src/pages/home/index.jsx
  src/pages/landing/index.jsx
  src/store/store.js
  src/styles/global.css
Labels: Feat, Design, Chore, Change

#26 🎨 Design: Nickname 변경 버튼 수정
  src/components/common/input/index.jsx
  src/pages/setting/index.jsx
Labels: Design

#27 ✨ Feat: 투두 및 캘린더 기능 완성
  public/button/checkBtn.svg
  public/button/deleteBtn.svg
  public/button/section3.svg
  public/iconGithub.svg
  public/password/eye1.svg
  public/password/eye2.svg
  src/App.jsx
  src/api/axios.js
  src/components/common/input/index.jsx
  src/components/layout/header/index.jsx
  src/components/shared/calendar/index.jsx
  src/components/shared/todo/index.jsx
  src/pages/home/index.jsx
  src/pages/landing/index.jsx
  src/pages/signin/index.jsx
  src/pages/signup/index.jsx
  src/store/store.js
  src/styles/global.css
  tailwind.config.js
Labels: Feat, Design, Refactor, Change

#28 ✨ Feat: Level 컴포넌트 제작
  src/components/shared/level/index.jsx
Labels: Feat

#29 ✨ Feat: Stack 컴포넌트 제작
  src/components/shared/stack/index.jsx
  src/lib/stack/index.jsx
  src/pages/setting/index.jsx
Labels: Feat, Design

#30 ✨ Feat: Stack 컴포넌트 분리 및 검색기능 추가
  package-lock.json
  package.json
  public/button/search.svg
  src/components/shared/stack/index.jsx
  src/lib/stack/index.jsx
  src/lib/stackList/index.jsx
  tailwind.config.js
Labels: Feat, Design, Chore

#33 ✨ Feat: 하단 레이아웃구간 컴포넌트 Swiper 추가
  package-lock.json
  package.json
  src/components/shared/stack/index.jsx
  src/lib/stack/index.jsx
  src/lib/stackList/index.jsx
  src/pages/home/index.jsx
  src/styles/global.css
Labels: Feat, Design, Chore, Change

#34 ✨ Feat: info 기능개발
  public/button/left.svg
  public/button/right.svg
  src/App.jsx
  src/components/layout/header/index.jsx
  src/components/shared/calendar/index.jsx
  src/components/shared/collection/index.jsx
  src/components/shared/info/index.jsx
  src/components/shared/level/index.jsx
  src/components/shared/stack/index.jsx
  src/components/shared/todo/index.jsx
  src/pages/home/index.jsx
  src/store/store.js
  src/styles/global.css
  tailwind.config.js
Labels: Fix, Feat, Design, Chore

#36 ✨ Feat: 모달 창 제작 (감자추가/감자획득/백준연동)
  public/images/grass.svg
  public/images/star-icon.svg
  src/components/modal/BaekjoonConnectModal.jsx
  src/components/modal/ChangePotatoModal.jsx
  src/components/modal/NewPotatoEarnedModal.jsx
  src/components/modal/PotatoInfoModal.jsx
  src/components/shared/collection/index.jsx
  src/components/shared/potato/index.jsx
  src/components/shared/stack/index.jsx
  src/pages/home/index.jsx
  src/pages/setting/index.jsx
  tailwind.config.js
Labels: Feat, Design

#37 ✨ Feat: alert 기능 제작
  public/button/section3.svg
  public/images/checkBtn.svg
  public/images/deleteBtn.svg
  public/images/iconGithub.svg
  public/images/left.svg
  public/images/pipe.svg
  public/images/potato.svg
  public/images/right.svg
  public/images/search.svg
  public/images/section1.svg
  public/images/section2.svg
  public/images/section3.svg
  public/images/setting.svg
  public/images/user.svg
  public/images/wave.svg
  public/images/wave2.svg
  public/images/write.svg
  public/landing/potato.jpeg
  src/assets/description.json
  src/assets/images/alertSuccess.svg
  src/assets/images/alertWarn.svg
  src/assets/images/crystalPotato.svg
  src/assets/images/dirtyPotato.svg
  src/assets/images/ghostPotato.svg
  src/assets/images/greenPotato.svg
  src/assets/images/jump.gif
  src/assets/images/levelFivePotato.svg
  src/assets/images/levelFourPotato.svg
  src/assets/images/levelOnePotato.svg
  src/assets/images/levelThreePotato.svg
  src/assets/images/levelTwoPotato.svg
  src/assets/images/shPotato.svg
  src/assets/images/winterPotato.svg
  src/assets/react.svg
  src/components/common/alert/index.jsx
  src/components/common/loading/index.jsx
  src/components/layout/header/index.jsx
  src/components/shared/calendar/index.jsx
  src/components/shared/info/index.jsx
  src/components/shared/level/index.jsx
  src/components/shared/potato/index.jsx
  src/components/shared/stack/index.jsx
  src/components/shared/todo/index.jsx
  src/pages/home/index.jsx
  src/pages/landing/index.jsx
  src/pages/signin/index.jsx
  src/styles/global.css
  tailwind.config.js
Labels: Feat, Design, Chore, Change

#38 ✨ Feat: UserUpdateModal 제작
  src/components/modal/BaekjoonConnectModal.jsx
  src/components/modal/NewPotatoEarnedModal.jsx
  src/components/modal/UserUpdateModal.jsx
  src/components/modal/index.js
  src/pages/home/index.jsx
  src/styles/global.css
  tailwind.config.js
Labels: Feat, Design, Change

#39 ✨ Feat: api 모듈화 진행
  package-lock.json
  package.json
  public/images/right-arrow.svg
  src/api/axios.js
  src/apis/api/attendance.js
  src/apis/api/auth.js
  src/apis/api/baekjoon.js
  src/apis/api/github.js
  src/apis/api/potato.js
  src/apis/api/stack.js
  src/apis/api/todo.js
  src/apis/services/token.js
  src/apis/utils/instance.js
  src/assets/images/Group.svg
  src/assets/images/crystalPotato.svg
  src/assets/images/dirtyPotato.svg
  src/assets/images/ghostPotato.svg
  src/assets/images/greenPotato.svg
  src/assets/images/levelFivePotato.svg
  src/assets/images/levelFourPotato.svg
  src/assets/images/levelOnePotato.svg
  src/assets/images/levelThreePotato.svg
  src/assets/images/levelTwoPotato.svg
  src/assets/images/shPotato.svg
  src/assets/images/winterPotato.svg
  src/components/layout/header/index.jsx
  src/components/shared/calendar/index.jsx
  src/components/shared/todo/index.jsx
  src/utils/storage.js
Labels: Feat, Chore, Change

#40 ♻️ Refactor: Collection 컴포넌트 이미지 선택 코드 수정
  src/components/modal/ChangePotatoModal.jsx
  src/components/modal/PotatoInfoModal.jsx
  src/components/shared/collection/index.jsx
  src/components/shared/potato/index.jsx
  src/pages/home/index.jsx
Labels: Feat, Refactor

#41 ♻️Refactor: 이미지 경로 수정
  public/collection/basicpotato.svg
  public/collection/potato.svg
  src/assets/images/coin.svg
  src/assets/images/downarrow.svg
  src/assets/images/uparrow.svg
  src/components/shared/collection/index.jsx
  src/components/shared/potato/index.jsx
Labels: Refactor, Chore, Change
