Repository OZ-Coding-School/oz_03_main-004-FE, pull requests merged in 2024-08, with the labels that each got.

#43 ✨ Feat: 로그인 기능 완성
  package.json
  public/images/logout.png
  src/App.jsx
  src/apis/api/attendance.js
  src/apis/api/auth.js
  src/apis/api/baekjoon.js
  src/apis/api/github.js
  src/apis/api/potato.js
  src/apis/api/stack.js
  src/apis/api/todo.js
  src/apis/services/calendarService.js
  src/apis/services/todoService.js
  src/apis/utils/instance.js
  src/components/layout/header/index.jsx
  src/components/modal/UserUpdateModal.jsx
  src/components/shared/calendar/index.jsx
  src/components/shared/info/index.jsx
  src/components/shared/potato/index.jsx
  src/components/shared/todo/index.jsx
  src/main.jsx
  src/pages/home/index.jsx
  src/pages/landing/index.jsx
  src/pages/oauthCallback/index.jsx
  src/store/dateStore.js
  src/store/userStore.js
  src/utils/storage.js
Labels: Docs, Feat, Refactor, Chore, Change

#44 🐛 Fix: 투두 완료 오류 수정
  src/App.jsx
  src/apis/api/github.js
  src/apis/api/todo.js
  src/apis/services/calendarService.js
  src/apis/services/todoService.js
  src/components/common/loading/index.jsx
  src/components/shared/calendar/index.jsx
  src/components/shared/info/index.jsx
  src/components/shared/todo/index.jsx
  src/pages/home/index.jsx
  src/pages/profile/index.jsx
  src/pages/setting/index.jsx
  src/store/todosCompleteStore.js
  src/store/userStore.js
Labels: Fix, Docs, Feat, Design, Chore, Change

#46 ✨ Feat: service 개발
  public/images/levelup.png
  src/apis/api/baekjoon.js
  src/apis/api/potato.js
  src/apis/api/stack.js
  src/apis/services/levelService.js
  src/apis/services/settingPageService.js
  src/apis/services/stackService.js
  src/apis/services/userUpdateService.js
  src/components/common/loading/index.jsx
  src/components/modal/BaekjoonConnectModal.jsx
  src/components/modal/UserUpdateModal.jsx
  src/components/shared/level/index.jsx
  src/components/shared/stack/index.jsx
  src/pages/setting/index.jsx
Labels: Docs, Feat, Design

#47 ✨ Feat: potato Store 생성
  src/apis/api/potato.js
  src/apis/services/collectionService.js
  src/components/modal/ChangePotatoModal.jsx
  src/components/modal/PotatoInfoModal.jsx
  src/components/shared/collection/index.jsx
  src/components/shared/potato/index.jsx
  src/pages/home/index.jsx
  src/store/potatoTypeStore.js
  src/store/usePotatoStore.js
Labels: Feat, Refactor

#49 🐛 자동로그인 기능 수정
  src/components/shared/calendar/index.jsx
  src/pages/landing/index.jsx
Labels: Fix, Docs
